// Use VS Code Rest Client
// https://marketplace.visualstudio.com/items?itemName=humao.rest-client


GET http://localhost:59862/users/get

####

POST http://localhost:59862/users/register
Content-Type: application/json

{
    "alias": "did:one37:56d6048b-466c-43e9-bcfa-9fb1a0950010"
}

####